theme = "github_dark"

[editor]
line-number = "absolute"
mouse = false
true-color = true
auto-completion = true
auto-format = true
auto-info = false
indent-heuristic = "tree-sitter"
popup-border = "none"
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = true
git-ignore = true

[editor.lsp]
display-inlay-hints = false

[editor.indent-guides]
render = true
