#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

leftwm-command 'UnloadTheme'

# Remove pipe
pipe='/tmp/lemonbar-fifo'
[[ -p "$pipe" ]] && rm "$pipe"

# Remove background
feh --bg-scale "$SCRIPTPATH/down.jpg"

pkill 'sxhkd'

pkill 'lemonbar'

pkill 'picom'
